server:
  port: 9001   # port: 0 recomendado si usas múltiples instancias + Eureka
  shutdown: graceful

spring:
  application:
    name: brand-sv

  datasource:
    # Prioridad: variables locales (IDE) -> variables Docker -> defaults seguros.
    url: jdbc:postgresql://${POSTGRES_HOST:${POSTGRES_NETWORK_HOST:${POSTGRES_LOCAL_HOST:localhost}}}:${POSTGRES_PORT:${POSTGRES_CONTAINER_PORT:${POSTGRES_HOST_PORT:5544}}}/${BRAND_DB:brand_db}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:root1234}
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: ${RABBITMQ_HOST:${RABBITMQ_NETWORK_HOST:${RABBITMQ_LOCAL_HOST:localhost}}}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:guest}
    password: ${RABBITMQ_DEFAULT_PASS:guest}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      micrometer:
        enabled: false
  lifecycle:
    timeout-per-shutdown-phase: 20s

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}}
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework: ${LOG_LEVEL_SPRING:INFO}

resilience4j:
  circuitbreaker:
    metrics:
      enabled: false
    instances:
      supplier-sv:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    metrics:
      enabled: false
    instances:
      supplier-sv:
        maxRetryAttempts: 5
        waitDuration: 10s

  ratelimiter:
    metrics:
      enabled: false
    instances:
      supplier-sv:
        limitForPeriod: 10
        limitRefreshPeriod: 5s
        timeoutDuration: 10s
        registerHealthIndicator: true
        eventConsumerBufferSize: 100

  timelimiter:
    metrics:
      enabled: false
    instances:
      supplier-sv:
        timeoutDuration: 2s
        cancelRunningFuture: true
      ImageFeignClientuploadImageMultipartFileString:
        timeoutDuration: 30s
        cancelRunningFuture: true
      ImageFeignClientreplaceImageMultipartFileStringString:
        timeoutDuration: 30s
        cancelRunningFuture: true
      ImageFeignClientdeleteImageStringString:
        timeoutDuration: 15s
        cancelRunningFuture: true

  bulkhead:
    metrics:
      enabled: false
    instances:
      suppliers-sv:
        maxWaitDuration: 5s
        maxConcurrentCalls: 5

default:
  message: Hi