# ============================
# PROD PROFILE - brand-sv
# ============================

spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: WARN
    com.crishof: INFO

management:
  tracing:
    sampling:
      probability: 0.1
  endpoint:
    health:
      show-details: never

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
