# ============================
# DEV PROFILE - Development with PostgreSQL (Docker)
# ============================

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:${POSTGRES_NETWORK_HOST:${POSTGRES_LOCAL_HOST:localhost}}}:${POSTGRES_PORT:${POSTGRES_CONTAINER_PORT:${POSTGRES_HOST_PORT:5544}}}/${IDENTITY_DB:identity_db}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:root1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:2525}

logging:
  level:
    root: WARN
    com.zaphirio: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  mail:
    enabled: ${MAIL_ENABLED:false}
  reset-password:
    base-url: ${RESET_PASSWORD_BASE_URL:http://localhost:5173/reset-password}
  accept-invite:
    base-url: ${ACCEPT_INVITE_BASE_URL:http://localhost:5173/accept-invite}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

