server:
  port: 9011

spring:
  cloud:
    discovery:
      enabled: true
  data:
    web:
      pageable:
        serialization-mode: via-dto
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:${POSTGRES_NETWORK_HOST:${POSTGRES_LOCAL_HOST:localhost}}}:${POSTGRES_PORT:${POSTGRES_CONTAINER_PORT:${POSTGRES_HOST_PORT:5544}}}/${PRODUCT_DB:product_db}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:root1234}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 20000
  rabbitmq:
    host: ${RABBITMQ_HOST:${RABBITMQ_NETWORK_HOST:${RABBITMQ_LOCAL_HOST:localhost}}}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:guest}
    password: ${RABBITMQ_DEFAULT_PASS:guest}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}}
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework: ${LOG_LEVEL_SPRING:INFO}

management:
  tracing:
    sampling:
      probability: 1.0
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,refresh
  endpoint:
    health:
      show-details: always


resilience4j:
  circuitbreaker:
    instances:
      department-service:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      department-service:
        maxRetryAttempts: 5
        waitDuration: 10s
  ratelimiter:
    instances:
      department-service:
        limitForPeriod: 10
        limitRefreshPeriod: 5s
        timeoutDuration: 10s
        registerHealthIndicator: true
        eventConsumerBufferSize: 100
  timelimiter:
    instances:
      department-service:
        timeoutDuration: 2s
        cancelRunningFuture: true
      ImageClientuploadMultipartFileString:
        timeoutDuration: 30s
        cancelRunningFuture: true
      ImageClientreplaceMultipartFileStringString:
        timeoutDuration: 30s
        cancelRunningFuture: true
      ImageClientdeleteStringString:
        timeoutDuration: 15s
        cancelRunningFuture: true
  bulkhead:
    instances:
      department-service:
        maxWaitDuration: 5s
        maxConcurrentCalls: 5

default:
  message: Hi